services:

  #NODE WEB
  nodeweb-container:
    build:
      context: .
      dockerfile: docker/node-web/Dockerfile
    depends_on:
      - postgres-container
      - redis-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-unifaat_dw}
      POSTGRES_USER: ${POSTGRES_USER:-unifaat_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-unifaat_password}
      POSTGRES_HOST: postgres_host
      POSTGRES_PORT: 5432
      NODE_WEB_PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-troque-este-segredo}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@petshop.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      REDIS_HOST: redis_host
      REDIS_PORT: 6379
    restart: unless-stopped
    networks:
      backend-network:
        aliases:
            - nodeweb_host
      frontend-network:
        aliases:
            - nodeweb_host

  #NGINX
  nginx-container:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - nodeweb-container
    networks:
      - frontend-network

  #POSTGRES
  postgres-container:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-unifaat_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-unifaat_password}
      POSTGRES_DB: ${POSTGRES_DB:-unifaat_dw}
      TZ: America/Sao_Paulo
    ports:
      - "6789:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql
    networks:
      backend-network:
        aliases:
          - postgres_host
      frontend-network:

  #REDIS CACHE
  redis-container:
    image: redis:8-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-volume:/data
    networks:
      backend-network:
        aliases:
          - redis_host

  #NODE CLI
  nodecli-container:
    build:
      context: .
      dockerfile: docker/node-web/Dockerfile
    depends_on:
      - postgres-container
      - redis-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-unifaat_dw}
      POSTGRES_USER: ${POSTGRES_USER:-unifaat_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-unifaat_password}
      POSTGRES_HOST: postgres_host
      POSTGRES_PORT: 5432
      NODE_WEB_PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-troque-este-segredo}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@petshop.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      REDIS_HOST: redis_host
      REDIS_PORT: 6379
    profiles:
      - cli
    command: ["node", "command.js"]
    networks:
      backend-network:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
    internal: true

volumes:
  postgres-volume:
  redis-volume:
